import { CardType } from "Game/Types";

export const getUnicodeForCard = (card: CardType) => {
  switch (card) {
    case CardType.ACE_OF_CLUBS:
      return "🃑";
    case CardType.TWO_OF_CLUBS:
      return "🃒";
    case CardType.THREE_OF_CLUBS:
      return "🃓";
    case CardType.FOUR_OF_CLUBS:
      return "🃔";
    case CardType.FIVE_OF_CLUBS:
      return "🃕";
    case CardType.SIX_OF_CLUBS:
      return "🃖";
    case CardType.SEVEN_OF_CLUBS:
      return "🃗";
    case CardType.EIGHT_OF_CLUBS:
      return "🃘";
    case CardType.NINE_OF_CLUBS:
      return "🃙";
    case CardType.TEN_OF_CLUBS:
      return "🃚";
    case CardType.JACK_OF_CLUBS:
      return "🃛";
    case CardType.QUEEN_OF_CLUBS:
      return "🃝";
    case CardType.KING_OF_CLUBS:
      return "🃞";
    case CardType.ACE_OF_DIAMONDS:
      return "🃁";
    case CardType.TWO_OF_DIAMONDS:
      return "🃂";
    case CardType.THREE_OF_DIAMONDS:
      return "🃃";
    case CardType.FOUR_OF_DIAMONDS:
      return "🃄";
    case CardType.FIVE_OF_DIAMONDS:
      return "🃅";
    case CardType.SIX_OF_DIAMONDS:
      return "🃆";
    case CardType.SEVEN_OF_DIAMONDS:
      return "🃇";
    case CardType.EIGHT_OF_DIAMONDS:
      return "🃈";
    case CardType.NINE_OF_DIAMONDS:
      return "🃉";
    case CardType.TEN_OF_DIAMONDS:
      return "🃊";
    case CardType.JACK_OF_DIAMONDS:
      return "🃋";
    case CardType.QUEEN_OF_DIAMONDS:
      return "🃍";
    case CardType.KING_OF_DIAMONDS:
      return "🃎";
    case CardType.ACE_OF_HEARTS:
      return "🂱";
    case CardType.TWO_OF_HEARTS:
      return "🂲";
    case CardType.THREE_OF_HEARTS:
      return "🂳";
    case CardType.FOUR_OF_HEARTS:
      return "🂴";
    case CardType.FIVE_OF_HEARTS:
      return "🂵";
    case CardType.SIX_OF_HEARTS:
      return "🂶";
    case CardType.SEVEN_OF_HEARTS:
      return "🂷";
    case CardType.EIGHT_OF_HEARTS:
      return "🂸";
    case CardType.NINE_OF_HEARTS:
      return "🂹";
    case CardType.TEN_OF_HEARTS:
      return "🂺";
    case CardType.JACK_OF_HEARTS:
      return "🂻";
    case CardType.QUEEN_OF_HEARTS:
      return "🂽";
    case CardType.KING_OF_HEARTS:
      return "🂾";
    case CardType.ACE_OF_SPADES:
      return "🂡";
    case CardType.TWO_OF_SPADES:
      return "🂢";
    case CardType.THREE_OF_SPADES:
      return "🂣";
    case CardType.FOUR_OF_SPADES:
      return "🂤";
    case CardType.FIVE_OF_SPADES:
      return "🂥";
    case CardType.SIX_OF_SPADES:
      return "🂦";
    case CardType.SEVEN_OF_SPADES:
      return "🂧";
    case CardType.EIGHT_OF_SPADES:
      return "🂨";
    case CardType.NINE_OF_SPADES:
      return "🂩";
    case CardType.TEN_OF_SPADES:
      return "🂪";
    case CardType.JACK_OF_SPADES:
      return "🂫";
    case CardType.QUEEN_OF_SPADES:
      return "🂭";
    case CardType.KING_OF_SPADES:
      return "🂮";
    case CardType.JOKER_A:
      return "🃟";
    case CardType.JOKER_B:
      return "🃟";
    default:
      return "";
  }
};
